name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0<3.0.0"

dependencies:
  flutter:
    sdk: flutter
  animated_text_kit: ^2.0.0
  cupertino_icons: ^0.1.2
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.15.5+3
  cloud_firestore: ^0.13.4+2
  firebase_storage: ^3.1.5
  modal_progress_hud: ^0.1.3
  provider: ^4.0.4
  image_picker: ^0.6.4
  google_sign_in: ^4.4.1
  image_cropper: ^1.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
  - images/
